DroneEnv = {
    "Flock_RPM": {
        "MAT_mar": [
            "hlsong/Drones_flock/rjjs1itw",
            "hlsong/Drones_flock/8gzqrav1",
            "hlsong/Drones_flock/8f2pme0g",
            "hlsong/Drones_flock/ilzh9c5g",
            "hlsong/Drones_flock/7239nu0t",
            "hlsong/Drones_flock/kmia44ie",
        ],
        "MAT_jpr": [
            "hlsong/Drones_flock/vb2uwky1",
            "hlsong/Drones_flock/1mo9opnr",
            "hlsong/Drones_flock/15guwv73",
            "hlsong/Drones_flock/jtwn1lqu",
        ],
        "MAT": [
            "hlsong/Drones_flock/ux4ce66d",
            "hlsong/Drones_flock/gciryqqe",
            "hlsong/Drones_flock/a8shrl07",
            "hlsong/Drones_flock/9cfil1u9",
            "hlsong/Drones_flock/kfe2pjjr",
        ],
        "MAPPO_mar": [
            "hlsong/Drones_flock/cl5vsdc7",
            "hlsong/Drones_flock/6bd328up",
            "hlsong/Drones_flock/r9eh9nle",
            "hlsong/Drones_flock/q3obh9jw",
            "hlsong/Drones_flock/zrijeiqc",
            "hlsong/Drones_flock/cfbuqzq3",
        ],
        "MAPPO_jpr": [
            "hlsong/Drones_flock/mz8hkeok",
            "hlsong/Drones_flock/1w0ye1dm",
            "hlsong/Drones_flock/uporlfu6",
            "hlsong/Drones_flock/h0f58u55",
            "hlsong/Drones_flock/5muy8uwy",
        ],
        "MAPPO": [
            "hlsong/Drones_flock/46f0l4ef",
            "hlsong/Drones_flock/lt6rcpwm",
            "hlsong/Drones_flock/qoszpjpg",
            "hlsong/Drones_flock/uqy2btef",
            "hlsong/Drones_flock/dn4ui78f",
        ],
    },
    "Flock_PID": {
        "MAT_mar": [
            "hlsong/Drones_flock_pid/m5bcdvaw",
            "hlsong/Drones_flock_pid/jepwikhf",
            "hlsong/Drones_flock_pid/d5ka7ind",
            "hlsong/Drones_flock_pid/sufsxong",
            "hlsong/Drones_flock_pid/64pyesjz",
        ],
        "MAT_jpr": [
            "hlsong/Drones_flock_pid/wg8742da",
            "hlsong/Drones_flock_pid/ssmfipww",
            "hlsong/Drones_flock_pid/lclt1zjr",
            "hlsong/Drones_flock_pid/9d7guy0c",
            "hlsong/Drones_flock_pid/7f5q6m1z",
        ],
        "MAT": [
            "hlsong/Drones_flock_pid/9c36hzb7",
            "hlsong/Drones_flock_pid/k7sjsowd",
            "hlsong/Drones_flock_pid/ejdwlcts",
            "hlsong/Drones_flock_pid/isfoqpgn",
            "hlsong/Drones_flock_pid/3ark0brj",
        ],
        "MAPPO_mar": [
            "hlsong/Drones_flock_pid/qdysdujy",
            "hlsong/Drones_flock_pid/cbdxdgjn",
            "hlsong/Drones_flock_pid/lwm2pq39",
            "hlsong/Drones_flock_pid/203knimm",
        ],
        "MAPPO_jpr": [
            "hlsong/Drones_flock_pid/dkrxhdlx",
            "hlsong/Drones_flock_pid/t1zobtrj",
            "hlsong/Drones_flock_pid/k2zecjvf",
            "hlsong/Drones_flock_pid/5auat003",
            "hlsong/Drones_flock_pid/uq8v2w79",
            "hlsong/Drones_flock_pid/rsuzj0jy",
            "hlsong/Drones_flock_pid/dn8lzc4w",
        ],
        "MAPPO": [
            "hlsong/Drones_flock_pid/9w5ll461",
            "hlsong/Drones_flock_pid/sucxjg7g",
            "hlsong/Drones_flock_pid/wh3g2zjm",
            "hlsong/Drones_flock_pid/7a63u5pi",
            "hlsong/Drones_flock_pid/j4hy1t6r",
            "hlsong/Drones_flock_pid/jcsyt8l6",
        ],
    },
    "LeaderFollower_RPM": {
        "MAT_mar": [
            "hlsong/Drones_leader/23n5fhhb",
            "hlsong/Drones_leader/0tu3jwut",
            "hlsong/Drones_leader/0r5i9tp9",
            "hlsong/Drones_leader/32tmd2pt",
            "hlsong/Drones_leader/b65f6eiw",
        ],
        "MAT_jpr": [
            "hlsong/Drones_leader/tjugth9x",
            "hlsong/Drones_leader/3ropuas1",
            "hlsong/Drones_leader/j72ler6o",
            "hlsong/Drones_leader/iz1n3xeg",
            "hlsong/Drones_leader/4ypec4ms",
            "hlsong/Drones_leader/hpivlqp8",
        ],
        "MAT": [
            "hlsong/Drones_leader/qhol5hc0",
            "hlsong/Drones_leader/atkqu7jx",
            "hlsong/Drones_leader/a17ddk9a",
            "hlsong/Drones_leader/ygb5cjsp",
            "hlsong/Drones_leader/hxum3mec",
            "hlsong/Drones_leader/ctb10s6x",
        ],
        "MAPPO_mar": [
            "hlsong/Drones_leader/lkbcfsge",
            "hlsong/Drones_leader/wd0h55nm",
            "hlsong/Drones_leader/gqrytw2x",
            "hlsong/Drones_leader/30kbxjfz",
            "hlsong/Drones_leader/feljt6s6",
            "hlsong/Drones_leader/skk5kz9c",
        ],
        "MAPPO_jpr": [
            "hlsong/Drones_leader/zkqv2yru",
            "hlsong/Drones_leader/g5gj8bbi",
            "hlsong/Drones_leader/byqnq7o1",
            "hlsong/Drones_leader/6u8fghil",
            "hlsong/Drones_leader/w0xo6yk8",
            "hlsong/Drones_leader/5ggphnu5",
        ],
        "MAPPO": [
            "hlsong/Drones_leader/i3o597pm",
            "hlsong/Drones_leader/e3b0hvom",
            "hlsong/Drones_leader/u3xiygse",
            "hlsong/Drones_leader/ecxi99sj",
            "hlsong/Drones_leader/i3svcuup",
        ],
    },
    "LeaderFollower_PID": {
        "MAT_mar": [
            "hlsong/Drones_leader_pid/loocf00l",
            "hlsong/Drones_leader_pid/4v369hiq",
            "hlsong/Drones_leader_pid/ljkz5cvj",
            "hlsong/Drones_leader_pid/e1wy3ue4",
            "hlsong/Drones_leader_pid/q9vu2el4",
            "hlsong/Drones_leader_pid/3y1r3wzw",
            "hlsong/Drones_leader_pid/jksjbam2",
        ],
        "MAT_jpr": [
            "hlsong/Drones_leader_pid/nv2sspun",
            "hlsong/Drones_leader_pid/ynj8yu9z",
            "hlsong/Drones_leader_pid/vr2teqh2",
            "hlsong/Drones_leader_pid/e35gpe02",
            "hlsong/Drones_leader_pid/youlwn4t",
            "hlsong/Drones_leader_pid/7sniqcru",
            "hlsong/Drones_leader_pid/7gi20y1o",
        ],
        "MAT": [
            "hlsong/Drones_leader_pid/uf74c22b",
            "hlsong/Drones_leader_pid/7yae6i9o",
            "hlsong/Drones_leader_pid/4rly25va",
            "hlsong/Drones_leader_pid/na1p5ogz",
            "hlsong/Drones_leader_pid/jglj5kzx",
            "hlsong/Drones_leader_pid/lm8k7sf4",
        ],
        "MAPPO_mar": [
            "hlsong/Drones_leader_pid/ni8yna2x",
            "hlsong/Drones_leader_pid/f74in6hi",
            "hlsong/Drones_leader_pid/sr9zlk52",
            "hlsong/Drones_leader_pid/p20flgaw",
            "hlsong/Drones_leader_pid/sp9l34cw",
        ],
        "MAPPO_jpr": [
            "hlsong/Drones_leader_pid/tfh6kq6m",
            "hlsong/Drones_leader_pid/ib4e8oxk",
            "hlsong/Drones_leader_pid/ny8o2k17",
            "hlsong/Drones_leader_pid/01i63064",
            "hlsong/Drones_leader_pid/debthn2c",
        ],
        "MAPPO": [
            "hlsong/Drones_leader_pid/42rm2fge",
            "hlsong/Drones_leader_pid/1insowm3",
            "hlsong/Drones_leader_pid/7plwbgbz",
            "hlsong/Drones_leader_pid/q63xg8gj",
            "hlsong/Drones_leader_pid/g9jl9vyt",
        ],
    },
    # "LeaderFollower_DYN": {
    #     "MAT_mar": [
    #         "hlsong/Drones_leader_DYN/y27efs0m",
    #         "hlsong/Drones_leader_DYN/gv5kcy2r",
    #         "hlsong/Drones_leader_DYN/huddld1z",
    #         "hlsong/Drones_leader_DYN/ywv99ov9",
    #         "hlsong/Drones_leader_DYN/4i1jmxtc",
    #         "hlsong/Drones_leader_DYN/k5rgkyf8",
    #     ],
    #     "MAT_jpr": [
    #         "hlsong/Drones_leader_DYN/935u6puk",
    #         "hlsong/Drones_leader_DYN/t1p7oq9w",
    #         "hlsong/Drones_leader_DYN/dxz1v0sr",
    #         "hlsong/Drones_leader_DYN/wlll6s5p",
    #         "hlsong/Drones_leader_DYN/bmsnt4vh",
    #         "hlsong/Drones_leader_DYN/4s2ewskm",
    #         "hlsong/Drones_leader_DYN/q7w050ul",
    #         "hlsong/Drones_leader_DYN/q9wgfrjk",
    #     ],
    #     "MAT": [
    #         "hlsong/Drones_leader_DYN/1hyads1f",
    #         "hlsong/Drones_leader_DYN/4jbeqnpf",
    #         "hlsong/Drones_leader_DYN/19jwfj95",
    #         "hlsong/Drones_leader_DYN/sjwrk6cr",
    #         "hlsong/Drones_leader_DYN/ed3d8nvp",
    #     ],
    #     "MAPPO_mar": [
    #         "hlsong/Drones_leader_DYN/fip4ayvp",
    #         "hlsong/Drones_leader_DYN/92de8a5t",
    #         "hlsong/Drones_leader_DYN/kfemahvp",
    #         "hlsong/Drones_leader_DYN/f8y9hqt8",
    #         "hlsong/Drones_leader_DYN/mba9dp1v",
    #         "hlsong/Drones_leader_DYN/2m4yj3ct",
    #         "hlsong/Drones_leader_DYN/vkx10di8",
    #         "hlsong/Drones_leader_DYN/gsunrrsu",
    #     ],
    #     "MAPPO_jpr": [
    #         "hlsong/Drones_leader_DYN/orcmes4v",
    #         "hlsong/Drones_leader_DYN/ogaesph8",
    #         "hlsong/Drones_leader_DYN/rxrcac6q",
    #         "hlsong/Drones_leader_DYN/hx7fgyzi",
    #         "hlsong/Drones_leader_DYN/g1hks4rr",
    #         "hlsong/Drones_leader_DYN/tkoj2h5l",
    #     ],
    #     "MAPPO": [
    #         "hlsong/Drones_leader_DYN/0jotsj9x",
    #         "hlsong/Drones_leader_DYN/7ztruui8",
    #         "hlsong/Drones_leader_DYN/ijestmoc",
    #         "hlsong/Drones_leader_DYN/h5rdg44p",
    #         "hlsong/Drones_leader_DYN/nziw5p30",
    #         "hlsong/Drones_leader_DYN/e84kave5",
    #     ],
    # },
}
