MujocoEnv = {
    "4x2-Agent Ant": {
        "MAT_mar": [
            "hlsong/mujoco_ant_4x2/oslr540g",
            "hlsong/mujoco_ant_4x2/rseibk6y",
            "hlsong/mujoco_ant_4x2/0xj68b57",
            "hlsong/mujoco_ant_4x2/gc3vgugx",
            "hlsong/mujoco_ant_4x2/4kdxtbei",
            "hlsong/mujoco_ant_4x2/0krjrh05",
        ],
        "MAT_jpr": [
            "hlsong/mujoco_ant_4x2/8hv8dfae",
            "hlsong/mujoco_ant_4x2/pvx2jsqx",
            "hlsong/mujoco_ant_4x2/syr57gmz",
            "hlsong/mujoco_ant_4x2/fusyh04y",
            "hlsong/mujoco_ant_4x2/kfynq4zu",
        ],
        "MAT": [
            "hlsong/mujoco_ant_4x2/g2099536",
            "hlsong/mujoco_ant_4x2/fs5cimox",
            "hlsong/mujoco_ant_4x2/5xai41ov",
            "hlsong/mujoco_ant_4x2/shdgewyg",
            "hlsong/mujoco_ant_4x2/piqzueg5",
        ],
        "MAPPO_mar": [
            "hlsong/mujoco_ant_4x2/6d906xfp",
            "hlsong/mujoco_ant_4x2/ybincewu",
            "hlsong/mujoco_ant_4x2/bp8meaan",
            "hlsong/mujoco_ant_4x2/tq6i1nc0",
            "hlsong/mujoco_ant_4x2/ycy1ob46",
        ],
        "MAPPO_jpr": [
            "hlsong/mujoco_ant_4x2/g0yfivh9",
            "hlsong/mujoco_ant_4x2/f41o0aop",
            "hlsong/mujoco_ant_4x2/b3kwi51d",
            "hlsong/mujoco_ant_4x2/mx7hqfsa",
            "hlsong/mujoco_ant_4x2/e0ypw65e",
        ],
        "MAPPO": [
            "hlsong/mujoco_ant_4x2/9le8r0vi",
            "hlsong/mujoco_ant_4x2/k18rxeqq",
            "hlsong/mujoco_ant_4x2/o3vtg89g",
            "hlsong/mujoco_ant_4x2/p8ba9ilv",
            "hlsong/mujoco_ant_4x2/pi0xk37a",
        ],
    },
    "8x1-Agent Ant": {
        "MAT_mar": [
            "hlsong/mujoco_ant_8x1/ckchag94",
            "hlsong/mujoco_ant_8x1/17vw6bhf",
            "hlsong/mujoco_ant_8x1/k9cpsycz",
            "hlsong/mujoco_ant_8x1/4npagnby",
            "hlsong/mujoco_ant_8x1/6trtqsp5",
        ],
        "MAT_jpr": [
            "hlsong/mujoco_ant_8x1/rqjdm4wf",
            "hlsong/mujoco_ant_8x1/1shwxleb",
            "hlsong/mujoco_ant_8x1/k9tqfetx",
            "hlsong/mujoco_ant_8x1/zo5mor93",
            "hlsong/mujoco_ant_8x1/86c67ui4",
        ],
        "MAT": [
            "hlsong/mujoco_ant_8x1/pc3ssusu",
            "hlsong/mujoco_ant_8x1/sykphknz",
            "hlsong/mujoco_ant_8x1/qgvixq28",
            "hlsong/mujoco_ant_8x1/jki9ojl5",
        ],
        "MAPPO_mar": [
            "hlsong/mujoco_ant_8x1/ci4hua6s",
            "hlsong/mujoco_ant_8x1/xpsdqnfr",
            "hlsong/mujoco_ant_8x1/iw906t8u",
            "hlsong/mujoco_ant_8x1/uxpomm1a",
        ],
        "MAPPO_jpr": [
            "hlsong/mujoco_ant_8x1/zy4lynj6",
            "hlsong/mujoco_ant_8x1/fx1bbs24",
            "hlsong/mujoco_ant_8x1/c2c7y6v7",
        ],
        "MAPPO": [
            "hlsong/mujoco_ant_8x1/78jhsfu1",
            "hlsong/mujoco_ant_8x1/i42xil4j",
            "hlsong/mujoco_ant_8x1/84z29ypc",
            "hlsong/mujoco_ant_8x1/cdxo48id",
            "hlsong/mujoco_ant_8x1/y0iqsy1v",
        ],
    },
    "6x1-Agent HalfCheetah": {
        "MAT_mar": [
            "hlsong/mujoco_half_6x1/opn8up26",
            "hlsong/mujoco_half_6x1/zvx57y67",
            "hlsong/mujoco_half_6x1/swcq7oj8",
            "hlsong/mujoco_half_6x1/yaxzfdnb",
            "hlsong/mujoco_half_6x1/2b53dw5n",
        ],
        "MAT_jpr": [
            "hlsong/mujoco_half_6x1/t46m3fzp",
            "hlsong/mujoco_half_6x1/9uco0niy",
            "hlsong/mujoco_half_6x1/2b4qt20w",
            "hlsong/mujoco_half_6x1/ey8s8a2l",
        ],
        "MAT": [
            "hlsong/mujoco_half_6x1/gwlx6k8j",
            "hlsong/mujoco_half_6x1/zs3csohr",
            "hlsong/mujoco_half_6x1/vcfleapp",
            "hlsong/mujoco_half_6x1/jrf4di37",
            "hlsong/mujoco_half_6x1/ubscbom5",
            "hlsong/mujoco_half_6x1/baypu4vw",
        ],
        "MAPPO_mar": [

            "hlsong/mujoco_half_6x1/gst8bfeu",
            "hlsong/mujoco_half_6x1/a1nawche",
            "hlsong/mujoco_half_6x1/epjv9iej",
            "hlsong/mujoco_half_6x1/b1rfaayq",
            "hlsong/mujoco_half_6x1/pp7jv7fa",
        ],
        "MAPPO_jpr": [
            "hlsong/mujoco_half_6x1/tt23f4br",
            "hlsong/mujoco_half_6x1/u5rmf6zi",
            "hlsong/mujoco_half_6x1/8txaqc1w",
            "hlsong/mujoco_half_6x1/778fhsnd",
            "hlsong/mujoco_half_6x1/61s2znsn",

        ],
        "MAPPO": [
            "hlsong/mujoco_half_6x1/e9wg2ay1",
            "hlsong/mujoco_half_6x1/ceopgew2",
            "hlsong/mujoco_half_6x1/xmvtketa",
            "hlsong/mujoco_half_6x1/s916d01w",
            "hlsong/mujoco_half_6x1/lr075x9t",
        ],
    },
    "3x2-Agent HalfCheetah": {
        "MAT_mar": [
            "hlsong/mujoco_half_3x2/cvqfhfgc",
            "hlsong/mujoco_half_3x2/xihalqk9",
            "hlsong/mujoco_half_3x2/1s3aig53",
            "hlsong/mujoco_half_3x2/8suvah9t",
            "hlsong/mujoco_half_3x2/nd3audc3",
            "hlsong/mujoco_half_3x2/oz0zsrxb",
            "hlsong/mujoco_half_3x2/c0mew7s6",
            "hlsong/mujoco_half_3x2/3i3ybzj6",
        ],
        "MAT_jpr": [
            "hlsong/mujoco_half_3x2/hzni4lu6",
            "hlsong/mujoco_half_3x2/fkp9g1uk",
            "hlsong/mujoco_half_3x2/ze6xdmp1",
            "hlsong/mujoco_half_3x2/eg8nmbl9",
            "hlsong/mujoco_half_3x2/wtulolnt",
        ],
        "MAT": [
            "hlsong/mujoco_half_3x2/xb6t76sm",
            "hlsong/mujoco_half_3x2/r19najky",
            "hlsong/mujoco_half_3x2/668scgkn",
            "hlsong/mujoco_half_3x2/q9ihe66w",
            "hlsong/mujoco_half_3x2/zuq71jwr",
            "hlsong/mujoco_half_3x2/a5dzgu0r",
            "hlsong/mujoco_half_3x2/rheh2ngd",
            "hlsong/mujoco_half_3x2/54pm0sxb",
        ],
        "MAPPO_mar": [
            "hlsong/mujoco_half_3x2/iedt6ube",
            "hlsong/mujoco_half_3x2/dnap14ay",
            "hlsong/mujoco_half_3x2/ebmgxryb",
            "hlsong/mujoco_half_3x2/m2sib9ho",
            "hlsong/mujoco_half_3x2/0idhc4q9",
        ],
        "MAPPO_jpr": [
            "hlsong/mujoco_half_3x2/t7eksdxq",
            "hlsong/mujoco_half_3x2/9eedhst7",
            "hlsong/mujoco_half_3x2/b0o0hysw",
            "hlsong/mujoco_half_3x2/1apq95h3",
        ],
        "MAPPO": [
            "hlsong/mujoco_half_3x2/d1i8my5x",
            "hlsong/mujoco_half_3x2/a9yssosr",
            "hlsong/mujoco_half_3x2/y89s30x4",
            "hlsong/mujoco_half_3x2/92yczzsz",
        ],
    },
    "3x1-Agent Hopper": {
        "MAT_mar": [
            "hlsong/mujoco_hopper_3x1/yi7ngrag",
            "hlsong/mujoco_hopper_3x1/wtet5c6u",
            "hlsong/mujoco_hopper_3x1/wonso09y",
            "hlsong/mujoco_hopper_3x1/bbnrxo4d",
        ],
        "MAT_jpr": [
            "hlsong/mujoco_hopper_3x1/aqhulumm",
            "hlsong/mujoco_hopper_3x1/5f0ffshv",
            "hlsong/mujoco_hopper_3x1/e0yuk8lt",
            "hlsong/mujoco_hopper_3x1/0c6mcao7",
            "hlsong/mujoco_hopper_3x1/92455422",
        ],
        "MAT": [
            "hlsong/mujoco_hopper_3x1/d9977387",
            "hlsong/mujoco_hopper_3x1/4jau3uga",
            "hlsong/mujoco_hopper_3x1/7dgi0yv3",
            "hlsong/mujoco_hopper_3x1/u8cxv4rc",
            "hlsong/mujoco_hopper_3x1/0411ynv1",
        ],
        "MAPPO_mar": [
            "hlsong/mujoco_hopper_3x1/5gj2nq8p",
            "hlsong/mujoco_hopper_3x1/09n9xmoq",
            "hlsong/mujoco_hopper_3x1/zib9gbgb",
            "hlsong/mujoco_hopper_3x1/u4xul9tc",
            "hlsong/mujoco_hopper_3x1/c04m5wpp",
            "hlsong/mujoco_hopper_3x1/kfdbb6e2",
        ],
        "MAPPO_jpr": [
            "hlsong/mujoco_hopper_3x1/7ffurkzx",
            "hlsong/mujoco_hopper_3x1/g6pwoqyf",
            "hlsong/mujoco_hopper_3x1/p63n7lxi",
            "hlsong/mujoco_hopper_3x1/2m3q93wg",
        ],
        "MAPPO": [
            "hlsong/mujoco_hopper_3x1/j2ay49u7",
            "hlsong/mujoco_hopper_3x1/w8qibrvs",
            "hlsong/mujoco_hopper_3x1/26guw3ci",
            "hlsong/mujoco_hopper_3x1/dxcc4xgu",
            "hlsong/mujoco_hopper_3x1/r9y37xnu",
        ],
    },
    "10x2-Agent swimmer": {
        "MAT_mar": [
            "hlsong/mujoco_swimmer_10x2/ike51euy",
            "hlsong/mujoco_swimmer_10x2/fuhcvri7",
            "hlsong/mujoco_swimmer_10x2/7l6zto2k",
            "hlsong/mujoco_swimmer_10x2/jh275znw",
            "hlsong/mujoco_swimmer_10x2/8hh11ygl",
            "hlsong/mujoco_swimmer_10x2/87v0o5l7",
            "hlsong/mujoco_swimmer_10x2/r57vh87z",
            "hlsong/mujoco_swimmer_10x2/x4c4jgth",
            "hlsong/mujoco_swimmer_10x2/kgzwbpfu",
            "hlsong/mujoco_swimmer_10x2/5b5zmw0d",
        ],
        "MAT_jpr": [
            "hlsong/mujoco_swimmer_10x2/ucvsq148",
            "hlsong/mujoco_swimmer_10x2/xmfj3v53",
            "hlsong/mujoco_swimmer_10x2/8kt2whu2",
            "hlsong/mujoco_swimmer_10x2/wz79vvxl",
        ],
        "MAT": [
            "hlsong/mujoco_swimmer_10x2/2sx48cfc",
            "hlsong/mujoco_swimmer_10x2/m3mvd4uw",
            "hlsong/mujoco_swimmer_10x2/6usp3be1",
            "hlsong/mujoco_swimmer_10x2/x3278ct0",
            "hlsong/mujoco_swimmer_10x2/s8lt1fp9",
        ],
        "MAPPO_mar": [
            "hlsong/mujoco_swimmer_10x2/w9gd6n6q",
            "hlsong/mujoco_swimmer_10x2/toox990n",
            "hlsong/mujoco_swimmer_10x2/6phprcom",
            "hlsong/mujoco_swimmer_10x2/qwmfnskh",
            "hlsong/mujoco_swimmer_10x2/2brm0sgz",
        ],
        "MAPPO_jpr": [
            "hlsong/mujoco_swimmer_10x2/lvgfyezs",
            "hlsong/mujoco_swimmer_10x2/t1t6hc21",
            "hlsong/mujoco_swimmer_10x2/z5k5gww5",
            "hlsong/mujoco_swimmer_10x2/pngwcfxg",
            "hlsong/mujoco_swimmer_10x2/tbqnmjqt",
        ],
        "MAPPO": [
            "hlsong/mujoco_swimmer_10x2/g0en7qfd",
            "hlsong/mujoco_swimmer_10x2/mwcvpnw5",
            "hlsong/mujoco_swimmer_10x2/v2cs08j4",
            "hlsong/mujoco_swimmer_10x2/qzqk3qrm",
            "hlsong/mujoco_swimmer_10x2/bp2gvo3w",
        ],
    },
    "6x1-Agent walker": {
        "MAT_mar": [
            "hlsong/mujoco_walker-6x1/we8d3313",
            "hlsong/mujoco_walker-6x1/y1ciyt0g",
            "hlsong/mujoco_walker-6x1/659yq30z",
            "hlsong/mujoco_walker-6x1/rzatyc7w",
        ],
        "MAT_jpr": [
            "hlsong/mujoco_walker-6x1/n8gtxbx0",
            "hlsong/mujoco_walker-6x1/hmhwlxo2",
            "hlsong/mujoco_walker-6x1/lb2uywl3",
            "hlsong/mujoco_walker-6x1/knd09uwj",
        ],
        "MAT": [
            "hlsong/mujoco_walker-6x1/dqoflw8s",
            "hlsong/mujoco_walker-6x1/82vcuyjr",
            "hlsong/mujoco_walker-6x1/rxuiy8fx",
            "hlsong/mujoco_walker-6x1/na9qcphs",
            "hlsong/mujoco_walker-6x1/5fkg3sgh",
        ],
        "MAPPO_mar": [
            "hlsong/mujoco_walker-6x1/t8svt2te",
            "hlsong/mujoco_walker-6x1/xhwtgy4i",
            "hlsong/mujoco_walker-6x1/5zzohm7p",
        ],
        "MAPPO_jpr": [
            "hlsong/mujoco_walker-6x1/oa35thhc",
            "hlsong/mujoco_walker-6x1/q9kfabxw",
            "hlsong/mujoco_walker-6x1/6bu7wli7",
        ],
        "MAPPO": [
            "hlsong/mujoco_walker-6x1/recvvzbi",
            "hlsong/mujoco_walker-6x1/bmfk9pvd",
            "hlsong/mujoco_walker-6x1/r9yx3e60",
            "hlsong/mujoco_walker-6x1/ubq3qqnh",
            "hlsong/mujoco_walker-6x1/j3ot2fed",
            "hlsong/mujoco_walker-6x1/cwkw2kjr",
        ],
    },
    "3x2-Agent walker": {
        "MAT_mar": [
            "hlsong/mujoco_walker_3x2/idlxeo5x",
            "hlsong/mujoco_walker_3x2/rrlg9183",
            "hlsong/mujoco_walker_3x2/ru1iv3oy",
        ],
        "MAT_jpr": [
            "hlsong/mujoco_walker_3x2/zzxiz397",
            "hlsong/mujoco_walker_3x2/nptecxd4",
            "hlsong/mujoco_walker_3x2/4z86131g",
            "hlsong/mujoco_walker_3x2/9oh91ntv",
            "hlsong/mujoco_walker_3x2/g2z7icfg",
            "hlsong/mujoco_walker_3x2/md1snqat",
        ],
        "MAT": [
            "hlsong/mujoco_walker_3x2/47oz7m9u",
            "hlsong/mujoco_walker_3x2/2jnwoh9c",
            "hlsong/mujoco_walker_3x2/jvivjp9k",
            "hlsong/mujoco_walker_3x2/mrolcvwk",
        ],
        "MAPPO_mar": [
            "hlsong/mujoco_walker_3x2/t02vew1a",
            "hlsong/mujoco_walker_3x2/31jl46d8",
            "hlsong/mujoco_walker_3x2/683v1rd2",
            "hlsong/mujoco_walker_3x2/12wf3qos",
            "hlsong/mujoco_walker_3x2/ecp2bfeo",
        ],
        "MAPPO_jpr": [
            "hlsong/mujoco_walker_3x2/s105n6z8",
            "hlsong/mujoco_walker_3x2/5uq02831",
            "hlsong/mujoco_walker_3x2/er11q6nc",
            "hlsong/mujoco_walker_3x2/dvoc1m7m",
        ],
        "MAPPO": [
            "hlsong/mujoco_walker_3x2/pmp77kf1",
            "hlsong/mujoco_walker_3x2/oiimhhsz",
            "hlsong/mujoco_walker_3x2/zw4m51xp",
            "hlsong/mujoco_walker_3x2/yi8qx1lc",
            "hlsong/mujoco_walker_3x2/288swhro",
        ],
    },
}
