def envlist():
    MujocoEnv = {
        "Ant-8x1-obsk=1": {
            "MAPPO_MaskAgengt": [  # N(0,1)
                "hlsong/mujoco_ant_8x1/emdsblf8",
                "hlsong/mujoco_ant_8x1/uyl7lhrs",
                "hlsong/mujoco_ant_8x1/kkqx8rzu",
                "hlsong/mujoco_ant_8x1/fbrskzrt",
            ],
            # "MAPPO_MaskAgengt": [ # zero
            #     "hlsong/mujoco_ant_8x1/msor4jj7",
            #     "hlsong/mujoco_ant_8x1/s99psjfo",
            #     "hlsong/mujoco_ant_8x1/1iff8grs",
            #     "hlsong/mujoco_ant_8x1/n2vzvyvk",
            # ],
            "MAPPO": [
                "hlsong/mujoco_ant_8x1/jt1al8zh",
                "hlsong/mujoco_ant_8x1/u12rp84s",
                "hlsong/mujoco_ant_8x1/lpqz3bjr",
                "hlsong/mujoco_ant_8x1/sw2fg4gw",
                "hlsong/mujoco_ant_8x1/6kbqtc2t",
            ],
        },
        # "Ant-8x1-obsk=0": {
        #     "MAPPO_MaskAgengt N(0,1)": [ # N(0,1)
        #         "hlsong/mujoco_ant_8x1/sncqjfc7",
        #         "hlsong/mujoco_ant_8x1/l6fdmui1",
        #         "hlsong/mujoco_ant_8x1/w8lpljnj",
        #         "hlsong/mujoco_ant_8x1/vk170yuy",
        #         "hlsong/mujoco_ant_8x1/bvao3gvb",
        #     ],
        #     "MAPPO_MaskAgengt zero": [ # zero
        #         "hlsong/mujoco_ant_8x1/xlsnwtmn",
        #         "hlsong/mujoco_ant_8x1/kvfw96ju",
        #         "hlsong/mujoco_ant_8x1/7b1tjrzc",
        #         "hlsong/mujoco_ant_8x1/e8cgoaz0",
        #         "hlsong/mujoco_ant_8x1/32j165ts",
        #         "hlsong/mujoco_ant_8x1/lasy69hs",
        #     ],
        #     "MAPPO ": [
        #         "hlsong/mujoco_ant_8x1/j11o94a2",
        #         "hlsong/mujoco_ant_8x1/rdmojjpx",
        #         "hlsong/mujoco_ant_8x1/5gvvintq",
        #         "hlsong/mujoco_ant_8x1/v444woxb",
        #         "hlsong/mujoco_ant_8x1/qv957j41",
        #     ],
        # },
        "Walker-6x1-obsk=1": {
            "MAPPO_MaskAgengt": [  # zero
                "hlsong/mujoco_walker-6x1/f0t6sbl3",
                "hlsong/mujoco_walker-6x1/fizkvhkl",
                "hlsong/mujoco_walker-6x1/olke5aw7",
                "hlsong/mujoco_walker-6x1/sqiaid51",
                "hlsong/mujoco_walker-6x1/3riqslxu",
                "hlsong/mujoco_walker-6x1/d4mzt00q",
            ],
            "MAPPO": [
                "hlsong/mujoco_walker-6x1/y4rruo1l",
                "hlsong/mujoco_walker-6x1/5v5g8e0j",
                "hlsong/mujoco_walker-6x1/vk06o4s5",
                "hlsong/mujoco_walker-6x1/f7h9hlq3",
                "hlsong/mujoco_walker-6x1/ipgphsb2",
            ],
        },
        "Half_cheetah-6x1-obsk=0": {
            "MAPPO_MaskAgengt": [  # zero
                "hlsong/mujoco_half/24btbxxc",
                "hlsong/mujoco_half/e8r1qccg",
                "hlsong/mujoco_half/npdwxhej",
                "hlsong/mujoco_half/qjtdbt0x",
                "hlsong/mujoco_half/qz0j0jlj",
            ],
            "MAPPO": [
                "hlsong/mujoco_half/fw00zacg",
                "hlsong/mujoco_half/2t179d49",
                "hlsong/mujoco_half/ozeti4ej",
                "hlsong/mujoco_half/k7qpr02u",
                "hlsong/mujoco_half/e5sn0w3w",
            ],
        },
        "Half_cheetah-6x1-obsk=1": {
            "MAPPO_MaskAgengt": [  # zero
                "hlsong/mujoco_half/ju4ouhr4",
                "hlsong/mujoco_half/ysnznu56",
                "hlsong/mujoco_half/xwnpuha6",
                "hlsong/mujoco_half/0mpw1yn2",
                "hlsong/mujoco_half/obijgl83",
                "hlsong/mujoco_half/8yiggy0z",
            ],
            "MAPPO": [
                "hlsong/mujoco_half/e9wg2ay1",
                "hlsong/mujoco_half/ceopgew2",
                "hlsong/mujoco_half/xmvtketa",
                "hlsong/mujoco_half/s916d01w",
                "hlsong/mujoco_half/lr075x9t",
            ],
        },
        "Hopper-3x1-obsk=1": {
            "MAPPO_MaskAgengt ": [  # N(0,1) sota
                "hlsong/mujoco_hopper/p6tvc4ir",
                "hlsong/mujoco_hopper/3df81ork",
                "hlsong/mujoco_hopper/6qhlrspb",
            ],
            # "MAPPO_MaskAgengt": [  # zero
            #     "hlsong/mujoco_hopper/vhm55u18",
            #     "hlsong/mujoco_hopper/u4xul9tc",
            #     "hlsong/mujoco_hopper/c04m5wpp",
            #     "hlsong/mujoco_hopper/kfdbb6e2",
            # ],
            "MAPPO": [
                "hlsong/mujoco_hopper/j2ay49u7",
                "hlsong/mujoco_hopper/w8qibrvs",
                "hlsong/mujoco_hopper/26guw3ci",
                "hlsong/mujoco_hopper/dxcc4xgu",
                "hlsong/mujoco_hopper/r9y37xnu",
            ],
        },
        "Ant-4x2-obsk=1": {
            "MAPPO_MaskAgengt": [  # zero # smooth = 7
                "hlsong/mujoco_ant_4x2/74gfdtzu",
                "hlsong/mujoco_ant_4x2/fdvkr9ea",
                "hlsong/mujoco_ant_4x2/x9tpib42",
                "hlsong/mujoco_ant_4x2/tzctdn1x",
            ],
            "MAPPO": [
                "hlsong/mujoco_ant_4x2/b72xwrz3",
                "hlsong/mujoco_ant_4x2/9le8r0vi",
                "hlsong/mujoco_ant_4x2/k18rxeqq",
                "hlsong/mujoco_ant_4x2/o3vtg89g",
                "hlsong/mujoco_ant_4x2/p8ba9ilv",
                "hlsong/mujoco_ant_4x2/pi0xk37a",
            ],
        },
        "Walker-3x2-obsk=1": {
            "MAPPO_MaskAgengt": [  # zero # smooth = 7
                "hlsong/mujoco_walker_3x2/jp46a4an",
                "hlsong/mujoco_walker_3x2/ukf8jg8w",
                "hlsong/mujoco_walker_3x2/63jljv3b",
                "hlsong/mujoco_walker_3x2/31iknwu4",
                "hlsong/mujoco_walker_3x2/41my7o9x",
            ],
            "MAPPO": [
                "hlsong/mujoco_walker_3x2/g99j68c2",
                "hlsong/mujoco_walker_3x2/svcazprs",
                "hlsong/mujoco_walker_3x2/dv3d45uo",
                "hlsong/mujoco_walker_3x2/9c4owawz",
                "hlsong/mujoco_walker_3x2/v5kjuz9t",
                "hlsong/mujoco_walker_3x2/eobqir0c",
            ],
        },
        "Half_cheetah-3x2-obsk=1": {
            "MAPPO_MaskAgengt": [  # zero # smooth = 7
                "hlsong/mujoco_half_3x2/ldhsswxm",
                "hlsong/mujoco_half_3x2/1vatv294",
                "hlsong/mujoco_half_3x2/fk9hs9b5",
                "hlsong/mujoco_half_3x2/oejq874n",
                "hlsong/mujoco_half_3x2/q7zz2sym",
                "hlsong/mujoco_half_3x2/wagbou9c",
            ],
            "MAPPO": [
                # "hlsong/mujoco_half_3x2/skayz5fv",
                "hlsong/mujoco_half_3x2/zababmbw",
                "hlsong/mujoco_half_3x2/5wvtemez",
                "hlsong/mujoco_half_3x2/huyp1bnm",
                "hlsong/mujoco_half_3x2/gjmfcsl3",
                # "hlsong/mujoco_half_3x2/tt4glc2k",
            ],
        },
        "Swimmer-6x1-obsk=1": {
            "MAPPO_MaskAgengt": [  # zero # smooth = 7
                "hlsong/mujoco_swimmer/6luzm22v",
                "hlsong/mujoco_swimmer/qmhowdur",
                "hlsong/mujoco_swimmer/7ssoucly",
                "hlsong/mujoco_swimmer/uyrrym6q",
                "hlsong/mujoco_swimmer/jzumdpke",
            ],
            "MAPPO": [
                "hlsong/mujoco_swimmer/g0en7qfd",
                "hlsong/mujoco_swimmer/mwcvpnw5",
                "hlsong/mujoco_swimmer/v2cs08j4",
                "hlsong/mujoco_swimmer/qzqk3qrm",
                "hlsong/mujoco_swimmer/bp2gvo3w",
            ],
        },
    }
    SMACEnv = {
        "3s_vs_5z": {
            "MAT_pma": [
                "hlsong/SMAC_3s_vs_5z/qyct2efu",
                "hlsong/SMAC_3s_vs_5z/36pmh8ey",
                "hlsong/SMAC_3s_vs_5z/pn7qbmdm",
                "hlsong/SMAC_3s_vs_5z/w0idto6c",
                "hlsong/SMAC_3s_vs_5z/xw68btg8",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_3s_vs_5z/hik9xqm8",
                "hlsong/SMAC_3s_vs_5z/11f23wkw",
                "hlsong/SMAC_3s_vs_5z/9idpu8tp",
            ],
            "MAT": [
                "hlsong/SMAC_3s_vs_5z/c9dko9qd",
                "hlsong/SMAC_3s_vs_5z/627s3vqi",
                "hlsong/SMAC_3s_vs_5z/a29fcu5e",
                "hlsong/SMAC_3s_vs_5z/74mmbxa8",
            ],
            "MAPPO_pma": [
                "hlsong/SMAC_3s_vs_5z/r5ivcjfe",
                "hlsong/SMAC_3s_vs_5z/0y0i9f4s",
                "hlsong/SMAC_3s_vs_5z/lvy01wll",
                "hlsong/SMAC_3s_vs_5z/jx9k6xcp",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_3s_vs_5z/9ojx6178",
                "hlsong/SMAC_3s_vs_5z/3lhbogd8",
                "hlsong/SMAC_3s_vs_5z/yquw1f6f",
                "hlsong/SMAC_3s_vs_5z/3378ijsb",
                "hlsong/SMAC_3s_vs_5z/j8xu7auv",
                "hlsong/SMAC_3s_vs_5z/ikbi4ch3",
            ],
            "MAPPO": [
                "hlsong/SMAC_3s_vs_5z/59ndduec",
                "hlsong/SMAC_3s_vs_5z/k4j86761",
                "hlsong/SMAC_3s_vs_5z/u78prr79",
                "hlsong/SMAC_3s_vs_5z/w9vrqjf2",
                "hlsong/SMAC_3s_vs_5z/hzzpribt",
            ],
        },
        "mmm": {
            "MAT_pma": [
                "hlsong/SMAC_mmm/xv3u5rlz",
                "hlsong/SMAC_mmm/01i9mjbz",
                "hlsong/SMAC_mmm/6pbnyewy",
                "hlsong/SMAC_mmm/4ko7i25c",
                "hlsong/SMAC_mmm/keabdwo7",
                "hlsong/SMAC_mmm/jaxl3gd1",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_mmm/er8naai4",
                "hlsong/SMAC_mmm/8dl9dyb4",
                "hlsong/SMAC_mmm/ri8qdp2n",
                "hlsong/SMAC_mmm/z7wfa6z9",
                "hlsong/SMAC_mmm/v4vdbn1a",
            ],
            "MAT": [
                "hlsong/SMAC_mmm/s887qbu3",
                "hlsong/SMAC_mmm/xd7mw701",
                "hlsong/SMAC_mmm/349vdxnl",
                "hlsong/SMAC_mmm/us3oflk5",
            ],
            "MAPPO_pma": [
                "hlsong/SMAC_mmm/wj53005z",
                "hlsong/SMAC_mmm/qnvkuxzc",
                "hlsong/SMAC_mmm/wpp5nxal",
                "hlsong/SMAC_mmm/dn6xf1az",
                "hlsong/SMAC_mmm/fx3bdybb",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_mmm/xk8jv9da",
                "hlsong/SMAC_mmm/3ednpk1c",
                "hlsong/SMAC_mmm/11x4eqza",
                "hlsong/SMAC_mmm/ckqcujkq",
                "hlsong/SMAC_mmm/jwktx2ju",
            ],
            "MAPPO": [
                "hlsong/SMAC_mmm/inifsd94",
                "hlsong/SMAC_mmm/vlpmdrng",
                "hlsong/SMAC_mmm/bfxdoj32",
                "hlsong/SMAC_mmm/mqbx3jd6",
                "hlsong/SMAC_mmm/zrs9hem2",
            ],
        },
        "3s5z": {
            "MAT_pma": [
                "hlsong/SMAC_3s5z/owuh2a4v",
                "hlsong/SMAC_3s5z/mvj88nxq",
                "hlsong/SMAC_3s5z/ow2ytulu",
                "hlsong/SMAC_3s5z/gdbi6pvr",
                "hlsong/SMAC_3s5z/xlyoey3s",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_3s5z/1mcij0rg",
                "hlsong/SMAC_3s5z/lb6f30ir",
                "hlsong/SMAC_3s5z/pcrlzavz",
                "hlsong/SMAC_3s5z/lf24yhlc",
                "hlsong/SMAC_3s5z/rnviip0r",
            ],
            "MAT": [
                "hlsong/SMAC_3s5z/gr4853f9",
                "hlsong/SMAC_3s5z/jozzqiub",
                "hlsong/SMAC_3s5z/9ufgh6x2",
                "hlsong/SMAC_3s5z/up22enyj",
                "hlsong/SMAC_3s5z/1mx1wbpi",
                "hlsong/SMAC_3s5z/jfqdzeil",
            ],
            "MAPPO_pma": [
                "hlsong/SMAC_3s5z/0hdbpfzj",
                "hlsong/SMAC_3s5z/bm878ffh",
                "hlsong/SMAC_3s5z/fyug206u",
                "hlsong/SMAC_3s5z/s0fmnwzu",
                "hlsong/SMAC_3s5z/310cpa5l",
                "hlsong/SMAC_3s5z/ycpkq1cd",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_3s5z/my0desi6",
                "hlsong/SMAC_3s5z/bgwxf8nf",
                "hlsong/SMAC_3s5z/fu2a3sme",
            ],
            "MAPPO": [
                "hlsong/SMAC_3s5z/3mlje0my",
                "hlsong/SMAC_3s5z/jywwojyb",
                "hlsong/SMAC_3s5z/68os40nd",
                "hlsong/SMAC_3s5z/8gsky889",
                "hlsong/SMAC_3s5z/k4llsimf",
            ],
        },
        "1c3s5z": {
            "MAT_pma": [
                "hlsong/SMAC_1c3s5z/dzuwmekt",
                "hlsong/SMAC_1c3s5z/0fyipd3a",
                "hlsong/SMAC_1c3s5z/rjqqo4dc",
                "hlsong/SMAC_1c3s5z/6olnx2aq",
                "hlsong/SMAC_1c3s5z/4g298wir",
                "hlsong/SMAC_1c3s5z/ju24sbsl",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_1c3s5z/vrw8stp1",
                "hlsong/SMAC_1c3s5z/lr9kht18",
                "hlsong/SMAC_1c3s5z/zzrji9bz",
            ],
            "MAT": [
                "hlsong/SMAC_1c3s5z/1xyibdcq",
                "hlsong/SMAC_1c3s5z/q6acjgmu",
                "hlsong/SMAC_1c3s5z/nuk4pnqk",
                "hlsong/SMAC_1c3s5z/y219jx1x",
            ],
            "MAPPO_pma": [
                "hlsong/SMAC_1c3s5z/q61653xl",
                "hlsong/SMAC_1c3s5z/ejpzltlg",
                "hlsong/SMAC_1c3s5z/tzkzzuz9",
                "hlsong/SMAC_1c3s5z/xe5uo6zn",
                "hlsong/SMAC_1c3s5z/ko4sroed",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_1c3s5z/a4hp39f6",
                "hlsong/SMAC_1c3s5z/fcj20jey",
                "hlsong/SMAC_1c3s5z/n23s9xdy",
                "hlsong/SMAC_1c3s5z/uuihrwuk",
            ],
            "MAPPO": [
                "hlsong/SMAC_1c3s5z/9pb0dnm3",
                "hlsong/SMAC_1c3s5z/tv4pe5kd",
                "hlsong/SMAC_1c3s5z/c9arw1s3",
                "hlsong/SMAC_1c3s5z/n8ifb2ba",
                "hlsong/SMAC_1c3s5z/fmpvxtuf",
            ],
        },
        "8m_vs_9m": {
            "MAT_pma": [
                "hlsong/SMAC_8m_vs_9m/l268palp",
                "hlsong/SMAC_8m_vs_9m/vkqfhmf2",
                "hlsong/SMAC_8m_vs_9m/79irtaeb",
                "hlsong/SMAC_8m_vs_9m/lmh1l36q",
                "hlsong/SMAC_8m_vs_9m/mty6p0au",
                "hlsong/SMAC_8m_vs_9m/8tz86wkb",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_8m_vs_9m/zqyuhl4t",
                "hlsong/SMAC_8m_vs_9m/o95ejbpp",
                "hlsong/SMAC_8m_vs_9m/0wrir2gk",
                "hlsong/SMAC_8m_vs_9m/3me3dzbo",
                "hlsong/SMAC_8m_vs_9m/n371zqd2",
            ],
            "MAT": [
                "hlsong/SMAC_8m_vs_9m/gkkjuxbj",
                "hlsong/SMAC_8m_vs_9m/ly9qnih6",
                "hlsong/SMAC_8m_vs_9m/0swty592",
                "hlsong/SMAC_8m_vs_9m/kt38oyjv",
                "hlsong/SMAC_8m_vs_9m/oc28cezf",
            ],
            "MAPPO_pma": [
                "hlsong/SMAC_8m_vs_9m/48k0btd8",
                "hlsong/SMAC_8m_vs_9m/568b5mmg",
                "hlsong/SMAC_8m_vs_9m/1hzad1ha",
                "hlsong/SMAC_8m_vs_9m/v2x3seuh",
                "hlsong/SMAC_8m_vs_9m/0q9vxxk5",
                "hlsong/SMAC_8m_vs_9m/upqksnvp",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_8m_vs_9m/9aw12a89",
                "hlsong/SMAC_8m_vs_9m/q24zpk7f",
                "hlsong/SMAC_8m_vs_9m/zu1bx46t",
                "hlsong/SMAC_8m_vs_9m/efnk3t42",
                "hlsong/SMAC_8m_vs_9m/xzez39kt",
            ],
            "MAPPO": [
                "hlsong/SMAC_8m_vs_9m/aj0cqqe0",
                "hlsong/SMAC_8m_vs_9m/bruzuh4z",
                "hlsong/SMAC_8m_vs_9m/9i4drxa3",
                "hlsong/SMAC_8m_vs_9m/gad9naiw",
            ],
        },
        "5m_vs_6m": {
            "MAT_pma": [
                "hlsong/SMAC_5m_vs_6m/gph0l05w",
                "hlsong/SMAC_5m_vs_6m/muuqrbag",
                "hlsong/SMAC_5m_vs_6m/0egpu1sz",
                "hlsong/SMAC_5m_vs_6m/vbs6x4z1",
                "hlsong/SMAC_5m_vs_6m/ys34pwhj",
                "hlsong/SMAC_5m_vs_6m/eii8odfe",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_5m_vs_6m/m5fyzlzb",
                "hlsong/SMAC_5m_vs_6m/egm41pyj",
                "hlsong/SMAC_5m_vs_6m/yxpf8lnu",
                "hlsong/SMAC_5m_vs_6m/r2bqy1v8",
                "hlsong/SMAC_5m_vs_6m/z7fo0w1z",
            ],
            "MAT": [
                "hlsong/SMAC_5m_vs_6m/bn68lxek",
                "hlsong/SMAC_5m_vs_6m/mew1fzgy",
                "hlsong/SMAC_5m_vs_6m/phhlrs8p",
                "hlsong/SMAC_5m_vs_6m/mididt8r",
            ],
            "MAPPO_pma": [
                "hlsong/SMAC_5m_vs_6m/7z7napq5",
                "hlsong/SMAC_5m_vs_6m/7p6pedlk",
                "hlsong/SMAC_5m_vs_6m/orux9riw",
                "hlsong/SMAC_5m_vs_6m/cafyrpca",
                "hlsong/SMAC_5m_vs_6m/8u3k9ox0",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_5m_vs_6m/oxj3iuf9",
                "hlsong/SMAC_5m_vs_6m/4fkwcz46",
                "hlsong/SMAC_5m_vs_6m/1gs0ubyn",
                "hlsong/SMAC_5m_vs_6m/gbd6tw50",
            ],
            "MAPPO": [
                "hlsong/SMAC_5m_vs_6m/21w6fwm0",
                "hlsong/SMAC_5m_vs_6m/qek9rg8r",
                "hlsong/SMAC_5m_vs_6m/83njxb88",
                "hlsong/SMAC_5m_vs_6m/rfu8d59z",
                "hlsong/SMAC_5m_vs_6m/vev92rys",
            ],
        },
        "10m_vs_11m": {
            "MAT_pma": [
                "hlsong/SMAC_10m_vs_11m/sws8qd4o",
                "hlsong/SMAC_10m_vs_11m/2cxpxq1t",
                "hlsong/SMAC_10m_vs_11m/02de3kl6",
                "hlsong/SMAC_10m_vs_11m/wg9dor26",
                "hlsong/SMAC_10m_vs_11m/hym5r6go",
                "hlsong/SMAC_10m_vs_11m/davbwm5j",
                "hlsong/SMAC_10m_vs_11m/i1plbbau",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_10m_vs_11m/rp8qinar",
                "hlsong/SMAC_10m_vs_11m/92spw711",
                "hlsong/SMAC_10m_vs_11m/klrdznam",
            ],
            "MAT": [
                "hlsong/SMAC_10m_vs_11m/ilrx6mn1",
                "hlsong/SMAC_10m_vs_11m/y00pdbq7",
                "hlsong/SMAC_10m_vs_11m/st3tqfks",
                "hlsong/SMAC_10m_vs_11m/t8i48tyj",
                "hlsong/SMAC_10m_vs_11m/gt5a29em",
            ],
            "MAPPO_pma": [
                "hlsong/SMAC_10m_vs_11m/jouykteg",
                "hlsong/SMAC_10m_vs_11m/b57dfpao",
                "hlsong/SMAC_10m_vs_11m/fllbn2u3",
                "hlsong/SMAC_10m_vs_11m/76s2e8it",
                "hlsong/SMAC_10m_vs_11m/g4kh5lz3",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_10m_vs_11m/3zown88c",
                "hlsong/SMAC_10m_vs_11m/gg39mcan",
                "hlsong/SMAC_10m_vs_11m/95dsvgo6",
                "hlsong/SMAC_10m_vs_11m/gcyc1tc8",
            ],
            "MAPPO": [
                "hlsong/SMAC_10m_vs_11m/05yqrdx7",
                "hlsong/SMAC_10m_vs_11m/879rj4pi",
                "hlsong/SMAC_10m_vs_11m/ig7dz4g2",
                "hlsong/SMAC_10m_vs_11m/ehi950ph",
            ],
        },
        "3s5z_vs_3s6z": {
            "MAT_pma": [
                "hlsong/SMAC_3s5z_vs_3s6z/bdqpyv8g",
                "hlsong/SMAC_3s5z_vs_3s6z/y4hj9xnn",
                "hlsong/SMAC_3s5z_vs_3s6z/hwwrn68l",
                "hlsong/SMAC_3s5z_vs_3s6z/6np3jvzf",
                "hlsong/SMAC_3s5z_vs_3s6z/nowyimom",
                "hlsong/SMAC_3s5z_vs_3s6z/omovs8wa",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_3s5z_vs_3s6z/xr3ftols",
                "hlsong/SMAC_3s5z_vs_3s6z/h39i86je",
                "hlsong/SMAC_3s5z_vs_3s6z/0ku7pthe",
                "hlsong/SMAC_3s5z_vs_3s6z/dbo0ryfo",
                "hlsong/SMAC_3s5z_vs_3s6z/4ustt8w4",
            ],
            "MAT": [
                "hlsong/SMAC_3s5z_vs_3s6z/3uyctvg9",
                "hlsong/SMAC_3s5z_vs_3s6z/cx3w0pj5",
                "hlsong/SMAC_3s5z_vs_3s6z/0dip7ccj",
                "hlsong/SMAC_3s5z_vs_3s6z/mq5n1yx8",
            ],
            "MAPPO_pma": [
                "hlsong/SMAC_3s5z_vs_3s6z/u9em3uor",
                "hlsong/SMAC_3s5z_vs_3s6z/em910s2s",
                "hlsong/SMAC_3s5z_vs_3s6z/kz952deh",
                "hlsong/SMAC_3s5z_vs_3s6z/5bkmru42",
                "hlsong/SMAC_3s5z_vs_3s6z/6dx92qmm",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_3s5z_vs_3s6z/iijijq3l",
                "hlsong/SMAC_3s5z_vs_3s6z/brxf11ok",
                "hlsong/SMAC_3s5z_vs_3s6z/wveq0eqd",
                "hlsong/SMAC_3s5z_vs_3s6z/i1pbr12p",
            ],
            "MAPPO": [
                "hlsong/SMAC_3s5z_vs_3s6z/w9lsily8",
                "hlsong/SMAC_3s5z_vs_3s6z/gup3oot7",
                "hlsong/SMAC_3s5z_vs_3s6z/zj1pm2uy",
                "hlsong/SMAC_3s5z_vs_3s6z/e23t45j4",
            ],
        },

    }
    env_list = {"mujoco": MujocoEnv, "StarCraft2": SMACEnv}
    return env_list


# if __name__ == "__main__":
#     project_name = "hlsong/mujoco_ant_8x1/"
#     with open("runlist.txt", "r") as f:
#         runlist = f.read().splitlines()
#         for run in runlist:
#             print(f"\"{project_name}{run}\",")
