def envlist():
    MujocoEnv = {
        "ant_4x2": {
            "MAT_mar": [
                "hlsong/mujoco_ant_4x2/8dh08961",
                "hlsong/mujoco_ant_4x2/4kdxtbei",
                "hlsong/mujoco_ant_4x2/mtthsttq",
                "hlsong/mujoco_ant_4x2/0krjrh05",
            ],
            "MAT_jpr": [
                "hlsong/mujoco_ant_4x2/h4txadr5",
                "hlsong/mujoco_ant_4x2/nr0jro65",
                "hlsong/mujoco_ant_4x2/ikghrq9v",
            ],
            "MAT": [
                "hlsong/mujoco_ant_4x2/g2099536",
                "hlsong/mujoco_ant_4x2/fs5cimox",
                "hlsong/mujoco_ant_4x2/5xai41ov",
                "hlsong/mujoco_ant_4x2/shdgewyg",
                "hlsong/mujoco_ant_4x2/piqzueg5",
            ],
            "MAPPO_mar": [
                "hlsong/mujoco_ant_4x2/r5uca067",
                "hlsong/mujoco_ant_4x2/uaf70lo3",
                "hlsong/mujoco_ant_4x2/ycy1ob46",
                "hlsong/mujoco_ant_4x2/7jgbmr7j",
                "hlsong/mujoco_ant_4x2/h06r41fo",
                "hlsong/mujoco_ant_4x2/xsvkx1ae",
                "hlsong/mujoco_ant_4x2/1cv9pyp1",
            ],
            "MAPPO_jpr": [
                "hlsong/mujoco_ant_4x2/km7g8exs",
                "hlsong/mujoco_ant_4x2/mktlat4t",
                "hlsong/mujoco_ant_4x2/e0ypw65e",
            ],
            "MAPPO": [
                "hlsong/mujoco_ant_4x2/9le8r0vi",
                "hlsong/mujoco_ant_4x2/k18rxeqq",
                "hlsong/mujoco_ant_4x2/o3vtg89g",
                "hlsong/mujoco_ant_4x2/p8ba9ilv",
                "hlsong/mujoco_ant_4x2/pi0xk37a",
            ],
        },
        "ant_8x1": {
            "MAT_mar": [
                "hlsong/mujoco_ant_8x1/17vw6bhf",
                "hlsong/mujoco_ant_8x1/k9cpsycz",
                "hlsong/mujoco_ant_8x1/4npagnby",
                "hlsong/mujoco_ant_8x1/6trtqsp5",
            ],
            "MAT_jpr": [
                "hlsong/mujoco_ant_8x1/zo5mor93",
                "hlsong/mujoco_ant_8x1/2ti9dn60",
                "hlsong/mujoco_ant_8x1/86c67ui4",
            ],
            "MAT": [
                "hlsong/mujoco_ant_8x1/pc3ssusu",
                "hlsong/mujoco_ant_8x1/sykphknz",
                "hlsong/mujoco_ant_8x1/qgvixq28",
                "hlsong/mujoco_ant_8x1/jki9ojl5",
            ],
            "MAPPO_mar": [
                "hlsong/mujoco_ant_8x1/ci4hua6s",
                "hlsong/mujoco_ant_8x1/xpsdqnfr",
                "hlsong/mujoco_ant_8x1/iw906t8u",
                "hlsong/mujoco_ant_8x1/uxpomm1a",
            ],
            "MAPPO_jpr": [
                "hlsong/mujoco_ant_8x1/fx1bbs24",
                "hlsong/mujoco_ant_8x1/c2c7y6v7",
            ],
            "MAPPO": [
                "hlsong/mujoco_ant_8x1/78jhsfu1",
                "hlsong/mujoco_ant_8x1/i42xil4j",
                "hlsong/mujoco_ant_8x1/84z29ypc",
                "hlsong/mujoco_ant_8x1/cdxo48id",
                "hlsong/mujoco_ant_8x1/y0iqsy1v",
            ],
        },
        "half_6x1": {
            "MAT_mar": [
                "hlsong/mujoco_half_6x1/yaxzfdnb",
                "hlsong/mujoco_half_6x1/a13qstj2",
                "hlsong/mujoco_half_6x1/2b53dw5n",
                "hlsong/mujoco_half_6x1/6vzlruzt",
                "hlsong/mujoco_half_6x1/1lmhzdn4",
            ],
            "MAT_jpr": [
                "hlsong/mujoco_half_6x1/2b4qt20w",
                "hlsong/mujoco_half_6x1/ey8s8a2l",
            ],
            "MAT": [
                "hlsong/mujoco_half_6x1/irkakfpb",
                "hlsong/mujoco_half_6x1/baypu4vw",
                "hlsong/mujoco_half_6x1/pse1833r",
                "hlsong/mujoco_half_6x1/p5tti5wp",
                "hlsong/mujoco_half_6x1/59umy3yf",
                "hlsong/mujoco_half_6x1/f6flf5mt",
                "hlsong/mujoco_half_6x1/cus8jz14",
                "hlsong/mujoco_half_6x1/0o47rapd",
                "hlsong/mujoco_half_6x1/mr4yrttz",
            ],
            "MAPPO_mar": [
                "hlsong/mujoco_half_6x1/gst8bfeu",
                "hlsong/mujoco_half_6x1/a1nawche",
                "hlsong/mujoco_half_6x1/epjv9iej",
                "hlsong/mujoco_half_6x1/b1rfaayq",
            ],
            "MAPPO_jpr": [
                "hlsong/mujoco_half_6x1/tt23f4br",
                "hlsong/mujoco_half_6x1/u5rmf6zi",
                "hlsong/mujoco_half_6x1/8txaqc1w",
                "hlsong/mujoco_half_6x1/778fhsnd",
                "hlsong/mujoco_half_6x1/pp7jv7fa",
            ],
            "MAPPO": [
                "hlsong/mujoco_half_6x1/e9wg2ay1",
                "hlsong/mujoco_half_6x1/ceopgew2",
                "hlsong/mujoco_half_6x1/xmvtketa",
                "hlsong/mujoco_half_6x1/s916d01w",
                "hlsong/mujoco_half_6x1/lr075x9t",
            ],
        },
        "half_3x2": {
            "MAT_mar": [
                "hlsong/mujoco_half_3x2/oz0zsrxb",
                "hlsong/mujoco_half_3x2/c0mew7s6",
                "hlsong/mujoco_half_3x2/d6a6i6i0",
                "hlsong/mujoco_half_3x2/3i3ybzj6",
            ],
            "MAT_jpr": [
                "hlsong/mujoco_half_3x2/z9q1m4j1",
                "hlsong/mujoco_half_3x2/y6d3w7er",
                "hlsong/mujoco_half_3x2/h5v4c3ni",
            ],
            "MAT": [
                "hlsong/mujoco_half_3x2/c9ggzj31",
                "hlsong/mujoco_half_3x2/iohjq1hl",
                "hlsong/mujoco_half_3x2/4j42xesu",
            ],
            "MAPPO_mar": [
                "hlsong/mujoco_half_3x2/iedt6ube",
                "hlsong/mujoco_half_3x2/dnap14ay",
                "hlsong/mujoco_half_3x2/ebmgxryb",
                "hlsong/mujoco_half_3x2/m2sib9ho",
                "hlsong/mujoco_half_3x2/0idhc4q9",
            ],
            "MAPPO_jpr": [
                "hlsong/mujoco_half_3x2/t7eksdxq",
                "hlsong/mujoco_half_3x2/9eedhst7",
                "hlsong/mujoco_half_3x2/b0o0hysw",
                "hlsong/mujoco_half_3x2/1apq95h3",
            ],
            "MAPPO": [
                "hlsong/mujoco_half_3x2/d1i8my5x",
                "hlsong/mujoco_half_3x2/a9yssosr",
                "hlsong/mujoco_half_3x2/y89s30x4",
                "hlsong/mujoco_half_3x2/92yczzsz",
            ],
        },
        "hopper_3x1": {
            "MAT_mar": [
                "hlsong/mujoco_hopper_3x1/yi7ngrag",
                "hlsong/mujoco_hopper_3x1/wtet5c6u",
                "hlsong/mujoco_hopper_3x1/wonso09y",
                "hlsong/mujoco_hopper_3x1/bbnrxo4d",
            ],
            "MAT_jpr": [
                "hlsong/mujoco_hopper_3x1/aqhulumm",
                "hlsong/mujoco_hopper_3x1/5f0ffshv",
                "hlsong/mujoco_hopper_3x1/e0yuk8lt",
                "hlsong/mujoco_hopper_3x1/0c6mcao7",
                "hlsong/mujoco_hopper_3x1/92455422",
            ],
            "MAT": [
                "hlsong/mujoco_hopper_3x1/d9977387",
                "hlsong/mujoco_hopper_3x1/4jau3uga",
                "hlsong/mujoco_hopper_3x1/7dgi0yv3",
                "hlsong/mujoco_hopper_3x1/u8cxv4rc",
                "hlsong/mujoco_hopper_3x1/0411ynv1",
            ],
            "MAPPO_mar": [
                "hlsong/mujoco_hopper_3x1/5gj2nq8p",
                "hlsong/mujoco_hopper_3x1/09n9xmoq",
                "hlsong/mujoco_hopper_3x1/zib9gbgb",
                "hlsong/mujoco_hopper_3x1/u4xul9tc",
                "hlsong/mujoco_hopper_3x1/c04m5wpp",
                "hlsong/mujoco_hopper_3x1/kfdbb6e2",
            ],
            "MAPPO_jpr": [
                "hlsong/mujoco_hopper_3x1/7ffurkzx",
                "hlsong/mujoco_hopper_3x1/g6pwoqyf",
                "hlsong/mujoco_hopper_3x1/p63n7lxi",
                "hlsong/mujoco_hopper_3x1/2m3q93wg",
            ],
            "MAPPO": [
                "hlsong/mujoco_hopper_3x1/j2ay49u7",
                "hlsong/mujoco_hopper_3x1/w8qibrvs",
                "hlsong/mujoco_hopper_3x1/26guw3ci",
                "hlsong/mujoco_hopper_3x1/dxcc4xgu",
                "hlsong/mujoco_hopper_3x1/r9y37xnu",
            ],
        },
        "swimmer_10x2": {
            "MAT_mar": [
                "hlsong/mujoco_swimmer_10x2/olwf2jl0",
                "hlsong/mujoco_swimmer_10x2/kgzwbpfu",
                "hlsong/mujoco_swimmer_10x2/5b5zmw0d",
                "hlsong/mujoco_swimmer_10x2/qmtyh05k",
            ],
            "MAT_jpr": [
                "hlsong/mujoco_swimmer_10x2/xmfj3v53",
                "hlsong/mujoco_swimmer_10x2/8kt2whu2",
                "hlsong/mujoco_swimmer_10x2/wz79vvxl",
            ],
            "MAT": [
                "hlsong/mujoco_swimmer_10x2/2sx48cfc",
                "hlsong/mujoco_swimmer_10x2/m3mvd4uw",
                "hlsong/mujoco_swimmer_10x2/6usp3be1",
                "hlsong/mujoco_swimmer_10x2/x3278ct0",
                "hlsong/mujoco_swimmer_10x2/s8lt1fp9",
            ],
            "MAPPO_mar": [
                "hlsong/mujoco_swimmer_10x2/wg7f59ro",
                "hlsong/mujoco_swimmer_10x2/9g5indk9",
                "hlsong/mujoco_swimmer_10x2/2brm0sgz",
                "hlsong/mujoco_swimmer_10x2/4kks5fy9",
                "hlsong/mujoco_swimmer_10x2/rvrtm4ih",
            ],
            "MAPPO_jpr": [
                "hlsong/mujoco_swimmer_10x2/lvgfyezs",
                "hlsong/mujoco_swimmer_10x2/t1t6hc21",
                "hlsong/mujoco_swimmer_10x2/z5k5gww5",
                "hlsong/mujoco_swimmer_10x2/pngwcfxg",
                "hlsong/mujoco_swimmer_10x2/tbqnmjqt",
            ],
            "MAPPO": [
                "hlsong/mujoco_swimmer_10x2/g0en7qfd",
                "hlsong/mujoco_swimmer_10x2/mwcvpnw5",
                "hlsong/mujoco_swimmer_10x2/v2cs08j4",
                "hlsong/mujoco_swimmer_10x2/qzqk3qrm",
                "hlsong/mujoco_swimmer_10x2/bp2gvo3w",
            ],
        },
        "walker-6x1": {
            "MAT_mar": [
                "hlsong/mujoco_walker-6x1/we8d3313",
                "hlsong/mujoco_walker-6x1/y1ciyt0g",
                "hlsong/mujoco_walker-6x1/659yq30z",
                "hlsong/mujoco_walker-6x1/rzatyc7w",
            ],
            "MAT_jpr": [
                "hlsong/mujoco_walker-6x1/n8gtxbx0",
                "hlsong/mujoco_walker-6x1/hmhwlxo2",
                "hlsong/mujoco_walker-6x1/lb2uywl3",
                "hlsong/mujoco_walker-6x1/knd09uwj",
            ],
            "MAT": [
                "hlsong/mujoco_walker-6x1/dqoflw8s",
                "hlsong/mujoco_walker-6x1/82vcuyjr",
                "hlsong/mujoco_walker-6x1/rxuiy8fx",
                "hlsong/mujoco_walker-6x1/na9qcphs",
                "hlsong/mujoco_walker-6x1/5fkg3sgh",
            ],
            "MAPPO_mar": [
                "hlsong/mujoco_walker-6x1/t8svt2te",
                "hlsong/mujoco_walker-6x1/xhwtgy4i",
                "hlsong/mujoco_walker-6x1/5zzohm7p",
            ],
            "MAPPO_jpr": [
                "hlsong/mujoco_walker-6x1/oa35thhc",
                "hlsong/mujoco_walker-6x1/q9kfabxw",
                "hlsong/mujoco_walker-6x1/6bu7wli7",
            ],
            "MAPPO": [
                "hlsong/mujoco_walker-6x1/recvvzbi",
                "hlsong/mujoco_walker-6x1/bmfk9pvd",
                "hlsong/mujoco_walker-6x1/r9yx3e60",
                "hlsong/mujoco_walker-6x1/ubq3qqnh",
                "hlsong/mujoco_walker-6x1/j3ot2fed",
                "hlsong/mujoco_walker-6x1/cwkw2kjr",
            ],
        },
        "walker_3x2": {
            "MAT_mar": [
                "hlsong/mujoco_walker_3x2/idlxeo5x",
                "hlsong/mujoco_walker_3x2/rrlg9183",
                "hlsong/mujoco_walker_3x2/ru1iv3oy",
            ],
            "MAT_jpr": [
                "hlsong/mujoco_walker_3x2/4z86131g",
                "hlsong/mujoco_walker_3x2/9oh91ntv",
                "hlsong/mujoco_walker_3x2/g2z7icfg",
                "hlsong/mujoco_walker_3x2/md1snqat",
            ],
            "MAT": [
                "hlsong/mujoco_walker_3x2/47oz7m9u",
                "hlsong/mujoco_walker_3x2/2jnwoh9c",
                "hlsong/mujoco_walker_3x2/jvivjp9k",
                "hlsong/mujoco_walker_3x2/mrolcvwk",
            ],
            "MAPPO_mar": [
                "hlsong/mujoco_walker_3x2/31jl46d8",
                "hlsong/mujoco_walker_3x2/683v1rd2",
                "hlsong/mujoco_walker_3x2/12wf3qos",
                "hlsong/mujoco_walker_3x2/ecp2bfeo",
            ],
            "MAPPO_jpr": [
                "hlsong/mujoco_walker_3x2/s105n6z8",
                "hlsong/mujoco_walker_3x2/5uq02831",
                "hlsong/mujoco_walker_3x2/er11q6nc",
                "hlsong/mujoco_walker_3x2/dvoc1m7m",
            ],
            "MAPPO": [
                "hlsong/mujoco_walker_3x2/pmp77kf1",
                "hlsong/mujoco_walker_3x2/oiimhhsz",
                "hlsong/mujoco_walker_3x2/zw4m51xp",
                "hlsong/mujoco_walker_3x2/yi8qx1lc",
                "hlsong/mujoco_walker_3x2/288swhro",
            ],
        },

    }
    SMACEnv = {
        "3s_vs_5z": {
            "MAT_mar": [
                "hlsong/SMAC_3s_vs_5z/qyct2efu",
                "hlsong/SMAC_3s_vs_5z/36pmh8ey",
                "hlsong/SMAC_3s_vs_5z/pn7qbmdm",
                "hlsong/SMAC_3s_vs_5z/w0idto6c",
                "hlsong/SMAC_3s_vs_5z/xw68btg8",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_3s_vs_5z/hik9xqm8",
                "hlsong/SMAC_3s_vs_5z/11f23wkw",
                "hlsong/SMAC_3s_vs_5z/9idpu8tp",
            ],
            "MAT": [
                "hlsong/SMAC_3s_vs_5z/c9dko9qd",
                "hlsong/SMAC_3s_vs_5z/627s3vqi",
                "hlsong/SMAC_3s_vs_5z/a29fcu5e",
                "hlsong/SMAC_3s_vs_5z/74mmbxa8",
            ],
            "MAPPO_mar": [
                "hlsong/SMAC_3s_vs_5z/r5ivcjfe",
                "hlsong/SMAC_3s_vs_5z/0y0i9f4s",
                "hlsong/SMAC_3s_vs_5z/lvy01wll",
                "hlsong/SMAC_3s_vs_5z/jx9k6xcp",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_3s_vs_5z/9ojx6178",
                "hlsong/SMAC_3s_vs_5z/3lhbogd8",
                "hlsong/SMAC_3s_vs_5z/yquw1f6f",
                "hlsong/SMAC_3s_vs_5z/3378ijsb",
                "hlsong/SMAC_3s_vs_5z/j8xu7auv",
                "hlsong/SMAC_3s_vs_5z/ikbi4ch3",
            ],
            "MAPPO": [
                "hlsong/SMAC_3s_vs_5z/59ndduec",
                "hlsong/SMAC_3s_vs_5z/k4j86761",
                "hlsong/SMAC_3s_vs_5z/u78prr79",
                "hlsong/SMAC_3s_vs_5z/w9vrqjf2",
                "hlsong/SMAC_3s_vs_5z/hzzpribt",
            ],
        },
        "mmm": {
            "MAT_mar": [
                "hlsong/SMAC_mmm/xv3u5rlz",
                "hlsong/SMAC_mmm/01i9mjbz",
                "hlsong/SMAC_mmm/6pbnyewy",
                "hlsong/SMAC_mmm/4ko7i25c",
                "hlsong/SMAC_mmm/keabdwo7",
                "hlsong/SMAC_mmm/jaxl3gd1",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_mmm/er8naai4",
                "hlsong/SMAC_mmm/8dl9dyb4",
                "hlsong/SMAC_mmm/ri8qdp2n",
                "hlsong/SMAC_mmm/z7wfa6z9",
                "hlsong/SMAC_mmm/v4vdbn1a",
            ],
            "MAT": [
                "hlsong/SMAC_mmm/s887qbu3",
                "hlsong/SMAC_mmm/xd7mw701",
                "hlsong/SMAC_mmm/349vdxnl",
                "hlsong/SMAC_mmm/us3oflk5",
            ],
            "MAPPO_mar": [
                "hlsong/SMAC_mmm/wj53005z",
                "hlsong/SMAC_mmm/qnvkuxzc",
                "hlsong/SMAC_mmm/wpp5nxal",
                "hlsong/SMAC_mmm/dn6xf1az",
                "hlsong/SMAC_mmm/fx3bdybb",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_mmm/xk8jv9da",
                "hlsong/SMAC_mmm/3ednpk1c",
                "hlsong/SMAC_mmm/11x4eqza",
                "hlsong/SMAC_mmm/ckqcujkq",
                "hlsong/SMAC_mmm/jwktx2ju",
            ],
            "MAPPO": [
                "hlsong/SMAC_mmm/inifsd94",
                "hlsong/SMAC_mmm/vlpmdrng",
                "hlsong/SMAC_mmm/bfxdoj32",
                "hlsong/SMAC_mmm/mqbx3jd6",
                "hlsong/SMAC_mmm/zrs9hem2",
            ],
        },
        "3s5z": {
            "MAT_mar": [
                "hlsong/SMAC_3s5z/owuh2a4v",
                "hlsong/SMAC_3s5z/mvj88nxq",
                "hlsong/SMAC_3s5z/ow2ytulu",
                "hlsong/SMAC_3s5z/gdbi6pvr",
                "hlsong/SMAC_3s5z/xlyoey3s",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_3s5z/1mcij0rg",
                "hlsong/SMAC_3s5z/lb6f30ir",
                "hlsong/SMAC_3s5z/pcrlzavz",
                "hlsong/SMAC_3s5z/lf24yhlc",
                "hlsong/SMAC_3s5z/rnviip0r",
            ],
            "MAT": [
                "hlsong/SMAC_3s5z/gr4853f9",
                "hlsong/SMAC_3s5z/jozzqiub",
                "hlsong/SMAC_3s5z/9ufgh6x2",
                "hlsong/SMAC_3s5z/up22enyj",
                "hlsong/SMAC_3s5z/1mx1wbpi",
                "hlsong/SMAC_3s5z/jfqdzeil",
            ],
            "MAPPO_mar": [
                "hlsong/SMAC_3s5z/0hdbpfzj",
                "hlsong/SMAC_3s5z/bm878ffh",
                "hlsong/SMAC_3s5z/fyug206u",
                "hlsong/SMAC_3s5z/s0fmnwzu",
                "hlsong/SMAC_3s5z/310cpa5l",
                "hlsong/SMAC_3s5z/ycpkq1cd",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_3s5z/my0desi6",
                "hlsong/SMAC_3s5z/bgwxf8nf",
                "hlsong/SMAC_3s5z/fu2a3sme",
            ],
            "MAPPO": [
                "hlsong/SMAC_3s5z/3mlje0my",
                "hlsong/SMAC_3s5z/jywwojyb",
                "hlsong/SMAC_3s5z/68os40nd",
                "hlsong/SMAC_3s5z/8gsky889",
                "hlsong/SMAC_3s5z/k4llsimf",
            ],
        },
        "1c3s5z": {
            "MAT_mar": [
                "hlsong/SMAC_1c3s5z/dzuwmekt",
                "hlsong/SMAC_1c3s5z/0fyipd3a",
                "hlsong/SMAC_1c3s5z/rjqqo4dc",
                "hlsong/SMAC_1c3s5z/6olnx2aq",
                "hlsong/SMAC_1c3s5z/4g298wir",
                "hlsong/SMAC_1c3s5z/ju24sbsl",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_1c3s5z/vrw8stp1",
                "hlsong/SMAC_1c3s5z/lr9kht18",
                "hlsong/SMAC_1c3s5z/zzrji9bz",
            ],
            "MAT": [
                "hlsong/SMAC_1c3s5z/1xyibdcq",
                "hlsong/SMAC_1c3s5z/q6acjgmu",
                "hlsong/SMAC_1c3s5z/nuk4pnqk",
                "hlsong/SMAC_1c3s5z/y219jx1x",
            ],
            "MAPPO_mar": [
                "hlsong/SMAC_1c3s5z/q61653xl",
                "hlsong/SMAC_1c3s5z/ejpzltlg",
                "hlsong/SMAC_1c3s5z/tzkzzuz9",
                "hlsong/SMAC_1c3s5z/xe5uo6zn",
                "hlsong/SMAC_1c3s5z/ko4sroed",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_1c3s5z/a4hp39f6",
                "hlsong/SMAC_1c3s5z/fcj20jey",
                "hlsong/SMAC_1c3s5z/n23s9xdy",
                "hlsong/SMAC_1c3s5z/uuihrwuk",
            ],
            "MAPPO": [
                "hlsong/SMAC_1c3s5z/9pb0dnm3",
                "hlsong/SMAC_1c3s5z/tv4pe5kd",
                "hlsong/SMAC_1c3s5z/c9arw1s3",
                "hlsong/SMAC_1c3s5z/n8ifb2ba",
                "hlsong/SMAC_1c3s5z/fmpvxtuf",
            ],
        },
        "8m_vs_9m": {
            "MAT_mar": [
                "hlsong/SMAC_8m_vs_9m/l268palp",
                "hlsong/SMAC_8m_vs_9m/vkqfhmf2",
                "hlsong/SMAC_8m_vs_9m/79irtaeb",
                "hlsong/SMAC_8m_vs_9m/lmh1l36q",
                "hlsong/SMAC_8m_vs_9m/mty6p0au",
                "hlsong/SMAC_8m_vs_9m/8tz86wkb",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_8m_vs_9m/zqyuhl4t",
                "hlsong/SMAC_8m_vs_9m/o95ejbpp",
                "hlsong/SMAC_8m_vs_9m/0wrir2gk",
                "hlsong/SMAC_8m_vs_9m/3me3dzbo",
                "hlsong/SMAC_8m_vs_9m/n371zqd2",
            ],
            "MAT": [
                "hlsong/SMAC_8m_vs_9m/gkkjuxbj",
                "hlsong/SMAC_8m_vs_9m/ly9qnih6",
                "hlsong/SMAC_8m_vs_9m/0swty592",
                "hlsong/SMAC_8m_vs_9m/kt38oyjv",
                "hlsong/SMAC_8m_vs_9m/oc28cezf",
            ],
            "MAPPO_mar": [
                "hlsong/SMAC_8m_vs_9m/48k0btd8",
                "hlsong/SMAC_8m_vs_9m/568b5mmg",
                "hlsong/SMAC_8m_vs_9m/1hzad1ha",
                "hlsong/SMAC_8m_vs_9m/v2x3seuh",
                "hlsong/SMAC_8m_vs_9m/0q9vxxk5",
                "hlsong/SMAC_8m_vs_9m/upqksnvp",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_8m_vs_9m/9aw12a89",
                "hlsong/SMAC_8m_vs_9m/q24zpk7f",
                "hlsong/SMAC_8m_vs_9m/zu1bx46t",
                "hlsong/SMAC_8m_vs_9m/efnk3t42",
                "hlsong/SMAC_8m_vs_9m/xzez39kt",
            ],
            "MAPPO": [
                "hlsong/SMAC_8m_vs_9m/aj0cqqe0",
                "hlsong/SMAC_8m_vs_9m/bruzuh4z",
                "hlsong/SMAC_8m_vs_9m/9i4drxa3",
                "hlsong/SMAC_8m_vs_9m/gad9naiw",
            ],
        },
        "5m_vs_6m": {
            "MAT_mar": [
                "hlsong/SMAC_5m_vs_6m/gph0l05w",
                "hlsong/SMAC_5m_vs_6m/muuqrbag",
                "hlsong/SMAC_5m_vs_6m/0egpu1sz",
                "hlsong/SMAC_5m_vs_6m/vbs6x4z1",
                "hlsong/SMAC_5m_vs_6m/ys34pwhj",
                "hlsong/SMAC_5m_vs_6m/eii8odfe",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_5m_vs_6m/m5fyzlzb",
                "hlsong/SMAC_5m_vs_6m/egm41pyj",
                "hlsong/SMAC_5m_vs_6m/yxpf8lnu",
                "hlsong/SMAC_5m_vs_6m/r2bqy1v8",
                "hlsong/SMAC_5m_vs_6m/z7fo0w1z",
            ],
            "MAT": [
                "hlsong/SMAC_5m_vs_6m/bn68lxek",
                "hlsong/SMAC_5m_vs_6m/mew1fzgy",
                "hlsong/SMAC_5m_vs_6m/phhlrs8p",
                "hlsong/SMAC_5m_vs_6m/mididt8r",
            ],
            "MAPPO_mar": [
                "hlsong/SMAC_5m_vs_6m/7z7napq5",
                "hlsong/SMAC_5m_vs_6m/7p6pedlk",
                "hlsong/SMAC_5m_vs_6m/orux9riw",
                "hlsong/SMAC_5m_vs_6m/cafyrpca",
                "hlsong/SMAC_5m_vs_6m/8u3k9ox0",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_5m_vs_6m/oxj3iuf9",
                "hlsong/SMAC_5m_vs_6m/4fkwcz46",
                "hlsong/SMAC_5m_vs_6m/1gs0ubyn",
                "hlsong/SMAC_5m_vs_6m/gbd6tw50",
            ],
            "MAPPO": [
                "hlsong/SMAC_5m_vs_6m/21w6fwm0",
                "hlsong/SMAC_5m_vs_6m/qek9rg8r",
                "hlsong/SMAC_5m_vs_6m/83njxb88",
                "hlsong/SMAC_5m_vs_6m/rfu8d59z",
                "hlsong/SMAC_5m_vs_6m/vev92rys",
            ],
        },
        "10m_vs_11m": {
            "MAT_mar": [
                "hlsong/SMAC_10m_vs_11m/sws8qd4o",
                "hlsong/SMAC_10m_vs_11m/2cxpxq1t",
                "hlsong/SMAC_10m_vs_11m/02de3kl6",
                "hlsong/SMAC_10m_vs_11m/wg9dor26",
                "hlsong/SMAC_10m_vs_11m/hym5r6go",
                "hlsong/SMAC_10m_vs_11m/davbwm5j",
                "hlsong/SMAC_10m_vs_11m/i1plbbau",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_10m_vs_11m/rp8qinar",
                "hlsong/SMAC_10m_vs_11m/92spw711",
                "hlsong/SMAC_10m_vs_11m/klrdznam",
            ],
            "MAT": [
                "hlsong/SMAC_10m_vs_11m/ilrx6mn1",
                "hlsong/SMAC_10m_vs_11m/y00pdbq7",
                "hlsong/SMAC_10m_vs_11m/st3tqfks",
                "hlsong/SMAC_10m_vs_11m/t8i48tyj",
                "hlsong/SMAC_10m_vs_11m/gt5a29em",
            ],
            "MAPPO_mar": [
                "hlsong/SMAC_10m_vs_11m/jouykteg",
                "hlsong/SMAC_10m_vs_11m/b57dfpao",
                "hlsong/SMAC_10m_vs_11m/fllbn2u3",
                "hlsong/SMAC_10m_vs_11m/76s2e8it",
                "hlsong/SMAC_10m_vs_11m/g4kh5lz3",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_10m_vs_11m/3zown88c",
                "hlsong/SMAC_10m_vs_11m/gg39mcan",
                "hlsong/SMAC_10m_vs_11m/95dsvgo6",
                "hlsong/SMAC_10m_vs_11m/gcyc1tc8",
            ],
            "MAPPO": [
                "hlsong/SMAC_10m_vs_11m/05yqrdx7",
                "hlsong/SMAC_10m_vs_11m/879rj4pi",
                "hlsong/SMAC_10m_vs_11m/ig7dz4g2",
                "hlsong/SMAC_10m_vs_11m/ehi950ph",
            ],
        },
        "3s5z_vs_3s6z": {
            "MAT_mar": [
                "hlsong/SMAC_3s5z_vs_3s6z/bdqpyv8g",
                "hlsong/SMAC_3s5z_vs_3s6z/y4hj9xnn",
                "hlsong/SMAC_3s5z_vs_3s6z/hwwrn68l",
                "hlsong/SMAC_3s5z_vs_3s6z/6np3jvzf",
                "hlsong/SMAC_3s5z_vs_3s6z/nowyimom",
                "hlsong/SMAC_3s5z_vs_3s6z/omovs8wa",
            ],
            "MAT_jpr": [
                "hlsong/SMAC_3s5z_vs_3s6z/xr3ftols",
                "hlsong/SMAC_3s5z_vs_3s6z/h39i86je",
                "hlsong/SMAC_3s5z_vs_3s6z/0ku7pthe",
                "hlsong/SMAC_3s5z_vs_3s6z/dbo0ryfo",
                "hlsong/SMAC_3s5z_vs_3s6z/4ustt8w4",
            ],
            "MAT": [
                "hlsong/SMAC_3s5z_vs_3s6z/3uyctvg9",
                "hlsong/SMAC_3s5z_vs_3s6z/cx3w0pj5",
                "hlsong/SMAC_3s5z_vs_3s6z/0dip7ccj",
                "hlsong/SMAC_3s5z_vs_3s6z/mq5n1yx8",
            ],
            "MAPPO_mar": [
                "hlsong/SMAC_3s5z_vs_3s6z/u9em3uor",
                "hlsong/SMAC_3s5z_vs_3s6z/em910s2s",
                "hlsong/SMAC_3s5z_vs_3s6z/kz952deh",
                "hlsong/SMAC_3s5z_vs_3s6z/5bkmru42",
                "hlsong/SMAC_3s5z_vs_3s6z/6dx92qmm",
            ],
            "MAPPO_jpr": [
                "hlsong/SMAC_3s5z_vs_3s6z/iijijq3l",
                "hlsong/SMAC_3s5z_vs_3s6z/brxf11ok",
                "hlsong/SMAC_3s5z_vs_3s6z/wveq0eqd",
                "hlsong/SMAC_3s5z_vs_3s6z/i1pbr12p",
            ],
            "MAPPO": [
                "hlsong/SMAC_3s5z_vs_3s6z/w9lsily8",
                "hlsong/SMAC_3s5z_vs_3s6z/gup3oot7",
                "hlsong/SMAC_3s5z_vs_3s6z/zj1pm2uy",
                "hlsong/SMAC_3s5z_vs_3s6z/e23t45j4",
            ],
        },

    }
    env_list = {"mujoco": MujocoEnv, "StarCraft2": SMACEnv}
    return env_list


# if __name__ == "__main__":
#     project_name = "hlsong/mujoco_ant_8x1/"
#     with open("runlist.txt", "r") as f:
#         runlist = f.read().splitlines()
#         for run in runlist:
#             print(f"\"{project_name}{run}\",")
