defaults:
    - envs:
        - StarCraft2
        - drone
        - mujoco
    - smooth:
        - mat
        - mappo

algo: mat
env_name: drone

store : True                        # 是否存储数据
save_path : './data'                # 数据存储路径
step_lenth : 0                      # 数据横坐标长度
save_plot : True                    # 是否存储图片
plot_path : './plot_result'         # 图片存储路径
smooth_length : 2                   # 数据平滑窗口长度
smooth_method : 2                   # 数据平滑方法

plot_all: False                     # 是否绘制所有图像
figure_type: 'OFMP'                 # 'OFOP' 一张图一个环境 or 'OFMP' 一张图多个环境 or 'MFOP' 多张图多个环境

Algo_Set:                          
    mat: ['MAT', 'MAT_mar', 'MAT_jpr']
    mappo: ['MAPPO', 'MAPPO_mar', 'MAPPO_jpr']
    all: ['MAPPO', 'MAPPO_mar', 'MAPPO_jpr', 'MAT', 'MAT_mar', 'MAT_jpr']
use_sub_name: True
algo_sub: {'MAT_mar': 'MA2CL', 'MAT_jpr': 'MAJOR' , 'MAPPO_mar': 'MAPPO+MA2CL' , 'MAPPPO_jpr': 'MAPPO+MAJOR'}

scenarios: ${envs.${env_name}.${algo}}          #地图
skip_scenarios: ['walker_3x2','half_3x2']       #跳过的地图
algo_set: ${Algo_Set.${algo}}                   #算法
smooth_dic: ${smooth.${algo}}                   #平滑参数


hue_name: algorithm                             #聚类标签
color:                                          #颜色
    palette: husl
    cls: 9
    index: [0,6,7]

data:
    step: ${envs.${env_name}.step}
    metric_key: ${envs.${env_name}.metric_key}
    local_step: Environment steps           #原始数据横坐标标签
    local_metric_key: Reward                #原始数据key
    smooth_metric_key: Smooth_Reward        #平滑后的数据key

plot_cfg:
    font_scale: 6                           # 字体大小
    linewidth: 5                            # 线宽
    font_size: 70                           # 字体大小
    figure_size: [18, 10]                   # 图片大小
    hue_order:                              # 绘图顺序
        mappo: ["MAPPO", "MAPPO+MAJOR", "MAPPO+MA2CL"]
        mat: ["MAT", "MAJOR", "MA2CL"]
    legend_order: [2,1,0]                   # 图例顺序
    xlabel: ${envs.${env_name}.xlabel}      # 横坐标标签
    ylabel: ${envs.${env_name}.ylabel}      # 纵坐标标签
    main_labels_anchor:                     # 图例位置
        {1: (0.5, -0.3),2: (0.5, -0.04), 3: (0.5, 0.05)}


hydra:
    job:
        chdir: False