    store : True                 # 是否存储数据
    save_path : './data'         # 数据存储路径
    step_lenth : None            # 数据横坐标长度
    smooth : 2                   # 数据平滑窗口长度
    smooth_method : 2            # 数据平滑方法
    save_plot : True             # 是否存储图片
    plot_path : './plot_result'  # 图片存储路径